export const navbarMobile = {
	open: [
		'right-0',
		'grid',
		'grid-cols-1',
		'grid-rows-[50dvh_20dvh_20dvh]',
		'z-3',
		'px-10',
		'py-5',
		'lg:p-0',
		'justify-center',
		'g-5',
		'absolute',
		'top-[100%]',
		'w-full',
		'overflow-hidden',
		'bg-blackp-500',
	],
	closed: [
		'grid',
		'grid-cols-1',
		'grid-rows-[0px_0px_0px]',

		'overflow-hidden',
		'absolute',
		'top-[100%]',
		'right-0',
		'bg-blackp-500',
		'w-full',
		'overflow-hidden',
		'z-3',
	],
	linksOpen: [
		'flex',
		'items-center',
		'justify-center',
		'gap-y-4',
		'gap-x-0',
		'flex-col',
		'opacity-100',
	],
	linksClosed: [
		'flex',
		'items-center',
		'justify-center',
		'gap-y-0',
		'gap-x-4',
		'flex-col',
		'opacity-0',
	],
	logoOpen: ['opacity-100'],
	logoClosed: ['opacity-0'],
	socialOpen: [
		'opacity-100',
		'flex',
		'gap-4.5',
		'items-center',
		'justify-center',
	],
	socialClosed: [
		'opacity-0',
		'flex',
		'gap-4.5',
		'items-center',
		'justify-center',
	],
};